/**
 * lucideIconMap — Shared name→component map for Lucide icons used by GameModules.
 *
 * GameModule schemas reference icons by string name (e.g., "MapPin", "Skull").
 * This map resolves those strings to actual Lucide React components at runtime,
 * used by OutlinerPanel, EntityPalette, and other UI that renders module-driven icons.
 */

import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Axe,
  BookOpen,
  Box,
  Building2,
  CalendarDays,
  Circle,
  Compass,
  Crown,
  Droplets,
  Fish,
  Flame,
  Folder,
  Gem,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Home,
  Key,
  Landmark,
  Layers,
  MapPin,
  Mountain,
  Music,
  Navigation,
  Package,
  Pickaxe,
  Radio,
  Route,
  ScrollText,
  Shield,
  Skull,
  Speaker,
  Star,
  Store,
  Sword,
  Swords,
  Target,
  TreePine,
  User,
  Users,
  Volume2,
  Wand2,
  Zap,
} from "lucide-react";

/** Map of Lucide icon names (as used in GameModule schemas) to React components. */
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  AlertTriangle,
  Axe,
  BookOpen,
  Box,
  Building2,
  CalendarDays,
  Circle,
  Compass,
  Crown,
  Droplets,
  Fish,
  Flame,
  Folder,
  Gem,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Home,
  Key,
  Landmark,
  Layers,
  MapPin,
  Mountain,
  Music,
  Navigation,
  Package,
  Pickaxe,
  Radio,
  Route,
  ScrollText,
  Shield,
  Skull,
  Speaker,
  Star,
  Store,
  Sword,
  Swords,
  Target,
  TreePine,
  User,
  Users,
  Volume2,
  Wand2,
  Zap,
};

/** Resolve a Lucide icon name to a component, falling back to Package. */
export function resolveLucideIcon(name: string): LucideIcon {
  return LUCIDE_ICON_MAP[name] ?? Package;
}
