/**
 * HyperscapeModule — Game module definition for the Hyperscape MMORPG.
 *
 * Declares all entity types, palette categories, outliner layers, and terrain
 * config for the Hyperscape game. Field definitions match the existing
 * Placed* interfaces from WorldStudio types.ts exactly.
 *
 * All entity types set `customEditor` to delegate to existing bespoke editors.
 * Remove `customEditor` on any type to switch it to the generic SchemaPropertyEditor.
 */

import type { GameModule } from "../GameModule";

export const HyperscapeModule: GameModule = {
  id: "hyperscape",
  name: "Hyperscape",
  version: "0.2.0",

  // ============== PALETTE CATEGORIES ==============

  paletteCategories: [
    {
      id: "npcs",
      label: "NPCs",
      icon: "Users",
      description: "Non-player characters, merchants, and quest givers",
    },
    {
      id: "world-features",
      label: "World Features",
      icon: "Globe",
      description: "Spawn points, teleports, and other world infrastructure",
    },
    {
      id: "creatures",
      label: "Creatures",
      icon: "Skull",
      description: "Mob spawns and boss encounters",
    },
    {
      id: "resources",
      label: "Resources",
      icon: "Gem",
      description: "Gathering nodes, mining spots, and resource areas",
    },
    {
      id: "structures",
      label: "Structures",
      icon: "Building2",
      description: "Stations, banks, altars, and crafting facilities",
    },
    {
      id: "pois",
      label: "Points of Interest",
      icon: "Landmark",
      description: "Dungeons, shrines, landmarks, and notable locations",
    },
    {
      id: "zones",
      label: "Zones & Regions",
      icon: "Map",
      description: "Danger sources, regions, and area boundaries",
    },
    {
      id: "water",
      label: "Water Bodies",
      icon: "Waves",
      description: "Rivers, lakes, and ponds",
    },
    {
      id: "audio",
      label: "Audio",
      icon: "Music",
      description: "Music zones, ambient sounds, and SFX triggers",
    },
    {
      id: "custom-assets",
      label: "Custom Assets",
      icon: "Package",
      description: "Imported or AI-generated 3D assets",
    },
  ],

  // ============== OUTLINER LAYERS ==============

  outlinerLayers: [
    {
      id: "npcs",
      label: "NPCs",
      icon: "Users",
      entityTypes: ["npc"],
    },
    {
      id: "world-features",
      label: "World Features",
      icon: "Globe",
      entityTypes: ["spawnPoint", "teleport"],
    },
    {
      id: "creatures",
      label: "Creatures",
      icon: "Skull",
      entityTypes: ["mobSpawn"],
    },
    {
      id: "resources",
      label: "Resources",
      icon: "Gem",
      entityTypes: ["resource", "mine"],
    },
    {
      id: "structures",
      label: "Structures",
      icon: "Building2",
      entityTypes: ["station"],
    },
    {
      id: "pois",
      label: "Points of Interest",
      icon: "Landmark",
      entityTypes: ["poi"],
    },
    {
      id: "zones",
      label: "Zones",
      icon: "Map",
      entityTypes: ["dangerSource", "region"],
    },
    {
      id: "water",
      label: "Water",
      icon: "Waves",
      entityTypes: ["waterBody"],
    },
    {
      id: "audio",
      label: "Audio",
      icon: "Music",
      entityTypes: ["musicZone", "ambientZone", "sfxTrigger"],
    },
    {
      id: "custom-assets",
      label: "Custom Assets",
      icon: "Package",
      entityTypes: ["customAsset"],
    },
  ],

  // ============== TERRAIN CONFIG ==============

  terrain: {
    enabled: true,
    tileSize: 4,
    biomes: [
      "plains",
      "forest",
      "desert",
      "snow",
      "swamp",
      "mountain",
      "beach",
      "canyon",
    ],
    procgen: true,
  },

  // ============== ENTITY TYPES ==============

  entityTypes: [
    // ───────── NPC ─────────
    // Matches PlacedNPC from WorldBuilder/types.ts
    {
      id: "npc",
      name: "NPC",
      icon: "User",
      color: "#3b82f6",
      paletteCategory: "npcs",
      outlinerLayer: "npcs",
      selectionType: "npc",
      storage: { stateKey: "npcs", type: "array" },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "NPC",
        },
        {
          key: "npcTypeId",
          label: "NPC Type",
          type: "string",
          section: "General",
          required: true,
          description: "NPC template ID from npcs.json",
        },
        {
          key: "storeId",
          label: "Store ID",
          type: "string",
          section: "Merchant",
          description: "Store ID for merchant NPCs",
        },
        {
          key: "dialogId",
          label: "Dialog ID",
          type: "string",
          section: "Dialog",
          description: "Dialog tree ID",
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "rotation",
          section: "Transform",
          default: 0,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "NPC",
        npcTypeId: "",
        parentContext: { type: "world" },
        rotation: 0,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: { shape: "capsule", scale: 1, yOffset: 0.5 },
      customEditor: "NPCProperties",
    },

    // ───────── Spawn Point ─────────
    // Matches PlacedSpawnPoint
    {
      id: "spawnPoint",
      name: "Spawn Point",
      icon: "MapPin",
      color: "#22c55e",
      paletteCategory: "world-features",
      outlinerLayer: "world-features",
      selectionType: "spawnPoint",
      storage: { stateKey: "spawnPoints", type: "array" },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Spawn Point",
        },
        {
          key: "spawnType",
          label: "Spawn Type",
          type: "select",
          section: "General",
          required: true,
          default: "initial",
          config: {
            options: [
              { value: "initial", label: "Initial Spawn" },
              { value: "death-respawn", label: "Death Respawn" },
              { value: "teleport-arrival", label: "Teleport Arrival" },
            ],
          },
        },
        {
          key: "capacity",
          label: "Capacity",
          type: "number",
          section: "General",
          default: 1,
          description: "Max players that can spawn here simultaneously",
          config: { min: 1, max: 100, step: 1 },
        },
        {
          key: "rotation",
          label: "Facing Direction",
          type: "rotation",
          section: "Transform",
          default: 0,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
        {
          key: "linkedAreaId",
          label: "Linked Area ID",
          type: "string",
          section: "Links",
          description: "Linked town or region ID",
        },
      ],
      defaults: {
        name: "Spawn Point",
        spawnType: "initial",
        capacity: 1,
        rotation: 0,
        position: { x: 0, y: 0, z: 0 },
        linkedAreaId: "",
        properties: {},
      },
      marker: { shape: "capsule", scale: 1, yOffset: 0.5 },
      templates: [
        {
          id: "initial-spawn",
          name: "Initial Spawn",
          description: "Default player spawn point at world start",
          defaults: { spawnType: "initial", capacity: 10 },
        },
        {
          id: "respawn",
          name: "Death Respawn",
          description: "Respawn point after player death",
          defaults: { spawnType: "death-respawn", capacity: 5 },
        },
        {
          id: "teleport-arrival",
          name: "Teleport Arrival",
          description: "Arrival point for teleport network",
          defaults: { spawnType: "teleport-arrival", capacity: 3 },
        },
      ],
      customEditor: "SpawnPointProperties",
    },

    // ───────── Teleport ─────────
    // Matches PlacedTeleport
    {
      id: "teleport",
      name: "Teleport",
      icon: "Zap",
      color: "#a855f7",
      paletteCategory: "world-features",
      outlinerLayer: "world-features",
      selectionType: "teleport",
      storage: { stateKey: "teleports", type: "array" },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Teleport",
        },
        {
          key: "cost",
          label: "Gold Cost",
          type: "number",
          section: "General",
          default: 0,
          description: "Gold cost to use this teleport",
          config: { min: 0, max: 100000, step: 1 },
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Teleport",
        connections: [],
        requirements: {},
        cost: 0,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: { shape: "cylinder", scale: 1.2, yOffset: 0 },
      templates: [
        {
          id: "free-teleport",
          name: "Free Teleport",
          description: "No-cost teleport node",
          defaults: { cost: 0 },
        },
        {
          id: "paid-teleport",
          name: "Paid Teleport",
          description: "Teleport requiring gold payment",
          defaults: { cost: 100 },
        },
      ],
      customEditor: "TeleportProperties",
    },

    // ───────── Mob Spawn ─────────
    // Matches PlacedMobSpawn
    {
      id: "mobSpawn",
      name: "Mob Spawn",
      icon: "Skull",
      color: "#f97316",
      paletteCategory: "creatures",
      outlinerLayer: "creatures",
      selectionType: "mobSpawn",
      storage: { stateKey: "mobSpawns", type: "array" },
      spatial: true,
      tracksSource: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Mob Spawn",
        },
        {
          key: "mobId",
          label: "Mob ID",
          type: "string",
          section: "General",
          required: true,
          description: "Mob template ID from npcs.json",
        },
        {
          key: "maxCount",
          label: "Max Count",
          type: "number",
          section: "Spawning",
          default: 3,
          description: "Maximum simultaneous instances",
          config: { min: 1, max: 50, step: 1 },
        },
        {
          key: "spawnRadius",
          label: "Spawn Radius",
          type: "number",
          section: "Spawning",
          default: 5,
          description: "Spawn radius from center (m)",
          config: { min: 1, max: 100, step: 1, unit: "m" },
        },
        {
          key: "respawnTicks",
          label: "Respawn Ticks",
          type: "number",
          section: "Spawning",
          default: 100,
          description: "Respawn delay in game ticks",
          config: { min: 1, max: 10000, step: 1 },
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Mob Spawn",
        mobId: "",
        maxCount: 3,
        spawnRadius: 5,
        respawnTicks: 100,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: {
        shape: "sphere",
        scale: 0.8,
        yOffset: 1,
        showRadius: true,
        radiusField: "spawnRadius",
      },
      customEditor: "MobSpawnProperties",
    },

    // ───────── Resource ─────────
    // Matches PlacedResource
    {
      id: "resource",
      name: "Resource",
      icon: "Gem",
      color: "#eab308",
      paletteCategory: "resources",
      outlinerLayer: "resources",
      selectionType: "resource",
      storage: { stateKey: "resources", type: "array" },
      spatial: true,
      tracksSource: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Resource",
        },
        {
          key: "resourceId",
          label: "Resource ID",
          type: "string",
          section: "General",
          required: true,
          description: "Gathering manifest ID (e.g., ore_copper, tree_oak)",
        },
        {
          key: "resourceType",
          label: "Type",
          type: "select",
          section: "General",
          required: true,
          default: "mining",
          config: {
            options: [
              { value: "mining", label: "Mining" },
              { value: "woodcutting", label: "Woodcutting" },
              { value: "fishing", label: "Fishing" },
              { value: "farming", label: "Farming" },
            ],
          },
        },
        {
          key: "modelVariant",
          label: "Model Variant",
          type: "number",
          section: "Visual",
          default: 0,
          config: { min: 0, max: 10, step: 1 },
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "rotation",
          section: "Transform",
          default: 0,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Resource",
        resourceId: "",
        resourceType: "mining",
        modelVariant: 0,
        rotation: 0,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: { shape: "cube", scale: 0.6, yOffset: 0.3 },
      customEditor: "ResourceProperties",
    },

    // ───────── Station ─────────
    // Matches PlacedStation
    {
      id: "station",
      name: "Station",
      icon: "Building2",
      color: "#8b5cf6",
      paletteCategory: "structures",
      outlinerLayer: "structures",
      selectionType: "station",
      storage: { stateKey: "stations", type: "array" },
      spatial: true,
      tracksSource: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Station",
        },
        {
          key: "stationType",
          label: "Station Type",
          type: "string",
          section: "General",
          required: true,
          description: "Type from stations.json",
        },
        {
          key: "bankId",
          label: "Bank ID",
          type: "string",
          section: "Station",
          description: "Bank ID (for bank stations)",
        },
        {
          key: "runeType",
          label: "Rune Type",
          type: "string",
          section: "Station",
          description: "Rune type (for runecrafting altars)",
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "rotation",
          section: "Transform",
          default: 0,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Station",
        stationType: "",
        rotation: 0,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: { shape: "cube", scale: 1, yOffset: 0.5 },
      customEditor: "StationProperties",
    },

    // ───────── POI ─────────
    // Matches PlacedPOI
    {
      id: "poi",
      name: "Point of Interest",
      icon: "Landmark",
      color: "#06b6d4",
      paletteCategory: "pois",
      outlinerLayer: "pois",
      selectionType: "poi",
      storage: { stateKey: "pois", type: "array" },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "POI",
        },
        {
          key: "category",
          label: "Category",
          type: "select",
          section: "General",
          required: true,
          default: "landmark",
          config: {
            options: [
              { value: "dungeon", label: "Dungeon" },
              { value: "shrine", label: "Shrine" },
              { value: "landmark", label: "Landmark" },
              { value: "resource_area", label: "Resource Area" },
              { value: "ruin", label: "Ruin" },
              { value: "camp", label: "Camp" },
              { value: "crossing", label: "Crossing" },
              { value: "waystation", label: "Waystation" },
              { value: "fishing_spot", label: "Fishing Spot" },
            ],
          },
        },
        {
          key: "importance",
          label: "Importance",
          type: "slider",
          section: "General",
          default: 0.5,
          description: "Weight for road connectivity (0-1)",
          config: { min: 0, max: 1, step: 0.05 },
        },
        {
          key: "radius",
          label: "Radius",
          type: "number",
          section: "Area",
          default: 20,
          description: "POI area radius (m)",
          config: { min: 1, max: 200, step: 1, unit: "m" },
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "POI",
        category: "landmark",
        importance: 0.5,
        radius: 20,
        connectedRoads: [],
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: {
        shape: "cylinder",
        scale: 0.8,
        yOffset: 0.5,
        showRadius: true,
        radiusField: "radius",
      },
      customEditor: "POIProperties",
    },

    // ───────── Water Body ─────────
    // Matches PlacedWaterBody
    {
      id: "waterBody",
      name: "Water Body",
      icon: "Waves",
      color: "#0ea5e9",
      paletteCategory: "water",
      outlinerLayer: "water",
      selectionType: "waterBody",
      storage: { stateKey: "waterBodies", type: "array" },
      spatial: false, // position is implicit from waypoints/polygon
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Water Body",
        },
        {
          key: "bodyType",
          label: "Body Type",
          type: "select",
          section: "General",
          required: true,
          default: "lake",
          config: {
            options: [
              { value: "river", label: "River" },
              { value: "lake", label: "Lake" },
              { value: "pond", label: "Pond" },
            ],
          },
        },
        {
          key: "surfaceY",
          label: "Surface Y",
          type: "number",
          section: "Water",
          description: "Water surface elevation",
          config: { step: 0.1 },
        },
        {
          key: "bermWidth",
          label: "Berm Width",
          type: "number",
          section: "Water",
          description: "River berm width",
          config: { min: 0, max: 50, step: 0.5, unit: "m" },
          visibleWhen: { field: "bodyType", equals: "river" },
        },
        {
          key: "valleyMultiplier",
          label: "Valley Multiplier",
          type: "number",
          section: "Water",
          description: "River valley depth",
          config: { min: 0, max: 5, step: 0.1 },
          visibleWhen: { field: "bodyType", equals: "river" },
        },
      ],
      defaults: { name: "Water Body", bodyType: "lake", properties: {} },
      marker: { shape: "cylinder", scale: 1, yOffset: 0 },
      customEditor: "WaterBodyProperties",
    },

    // ───────── Region ─────────
    // Matches PlacedRegion
    {
      id: "region",
      name: "Region",
      icon: "Map",
      color: "#10b981",
      paletteCategory: "zones",
      outlinerLayer: "zones",
      selectionType: "region",
      storage: { stateKey: "regions", type: "array" },
      spatial: false, // regions are defined by tile keys, not a single position
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Region",
        },
        {
          key: "description",
          label: "Description",
          type: "string",
          section: "General",
        },
        {
          key: "tags",
          label: "Tags",
          type: "tags",
          section: "General",
          description: "Filtering tags (e.g., starter, forest, mining-hub)",
        },
        {
          key: "biomeOverride",
          label: "Biome Override",
          type: "string",
          section: "Terrain",
          description: "Override biome within this region",
        },
        {
          key: "musicTrack",
          label: "Music Track",
          type: "string",
          section: "Audio",
          description: "Music track ID for this region",
        },
        {
          key: "ambientSound",
          label: "Ambient Sound",
          type: "string",
          section: "Audio",
          description: "Ambient sound for this region",
        },
      ],
      defaults: { name: "Region", description: "", tileKeys: [], tags: [] },
      marker: { shape: "billboard", scale: 1, yOffset: 2 },
      customEditor: "RegionProperties",
    },

    // ───────── Danger Source ─────────
    // Matches PlacedDangerSource
    {
      id: "dangerSource",
      name: "Danger Source",
      icon: "AlertTriangle",
      color: "#ef4444",
      paletteCategory: "zones",
      outlinerLayer: "zones",
      selectionType: "dangerSource",
      storage: { stateKey: "dangerSources", type: "array" },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Danger Source",
        },
        {
          key: "description",
          label: "Description",
          type: "string",
          section: "General",
          description: "Optional description for tooltips",
        },
        {
          key: "intensity",
          label: "Intensity",
          type: "slider",
          section: "Danger",
          default: 1,
          description: "Adds to biome difficulty scalar (0-3)",
          config: { min: 0, max: 3, step: 0.1 },
        },
        {
          key: "radius",
          label: "Radius",
          type: "number",
          section: "Danger",
          default: 50,
          description: "Radius of influence (m)",
          config: { min: 1, max: 500, step: 1, unit: "m" },
        },
        {
          key: "falloffCurve",
          label: "Falloff Curve",
          type: "slider",
          section: "Danger",
          default: 2,
          description: "How quickly intensity falls off with distance",
          config: { min: 0.1, max: 10, step: 0.1 },
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Danger Source",
        radius: 50,
        intensity: 1,
        falloffCurve: 2,
        position: { x: 0, y: 0, z: 0 },
      },
      marker: {
        shape: "sphere",
        scale: 0.8,
        yOffset: 1,
        showRadius: true,
        radiusField: "radius",
      },
      templates: [
        {
          id: "low-danger",
          name: "Low Danger",
          description: "Mild danger zone for starter areas",
          defaults: { intensity: 0.5, radius: 30, falloffCurve: 3 },
        },
        {
          id: "medium-danger",
          name: "Medium Danger",
          description: "Moderate danger for mid-level zones",
          defaults: { intensity: 1.5, radius: 50, falloffCurve: 2 },
        },
        {
          id: "high-danger",
          name: "High Danger",
          description: "Severe danger for endgame areas",
          defaults: { intensity: 3, radius: 80, falloffCurve: 1 },
        },
      ],
      customEditor: "DangerSourceProperties",
    },

    // ───────── Mine ─────────
    // Matches PlacedMine
    {
      id: "mine",
      name: "Mine",
      icon: "Mountain",
      color: "#78716c",
      paletteCategory: "resources",
      outlinerLayer: "resources",
      selectionType: "mine",
      storage: { stateKey: "mines", type: "array" },
      spatial: true,
      tracksSource: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Mine",
        },
        {
          key: "biome",
          label: "Biome",
          type: "string",
          section: "General",
          readOnly: true,
        },
        {
          key: "tierIndex",
          label: "Tier",
          type: "number",
          section: "General",
          readOnly: true,
          description: "Difficulty tier index",
        },
        {
          key: "radius",
          label: "Radius",
          type: "number",
          section: "Area",
          default: 20,
          description: "Base mine area radius (m)",
          config: { min: 15, max: 25, step: 1, unit: "m" },
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Mine",
        radius: 20,
        biome: "",
        tierIndex: 0,
        radialOffsets: [],
        entryAngle: 0,
        oreRocks: [],
        source: "procgen",
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: {
        shape: "cylinder",
        scale: 1.5,
        yOffset: 0,
        showRadius: true,
        radiusField: "radius",
      },
    },

    // ───────── Custom Asset ─────────
    // Matches PlacedCustomAsset
    {
      id: "customAsset",
      name: "Custom Asset",
      icon: "Package",
      color: "#ec4899",
      paletteCategory: "custom-assets",
      outlinerLayer: "custom-assets",
      selectionType: "customAsset",
      storage: { stateKey: "customAssets", type: "array" },
      spatial: true,
      tracksSource: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Custom Asset",
        },
        {
          key: "assetId",
          label: "Asset ID",
          type: "string",
          section: "Asset",
          required: true,
          description: "Asset Forge asset ID",
        },
        {
          key: "assetName",
          label: "Asset Name",
          type: "string",
          section: "Asset",
          readOnly: true,
        },
        {
          key: "modelPath",
          label: "Model Path",
          type: "string",
          section: "Asset",
          description: "Model file path override",
        },
        {
          key: "scale",
          label: "Scale",
          type: "number",
          section: "Transform",
          default: 1,
          config: { min: 0.01, max: 100, step: 0.1 },
        },
        {
          key: "rotation",
          label: "Rotation",
          type: "rotation",
          section: "Transform",
          default: 0,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "Custom Asset",
        assetId: "",
        assetName: "",
        scale: 1,
        rotation: 0,
        position: { x: 0, y: 0, z: 0 },
        properties: {},
      },
      marker: { shape: "model", scale: 1, yOffset: 0 },
      customEditor: "CustomAssetProperties",
    },

    // ───────── Music Zone ─────────
    // Matches MusicZone (audio layer)
    {
      id: "musicZone",
      name: "Music Zone",
      icon: "Music",
      color: "#6366f1",
      paletteCategory: "audio",
      outlinerLayer: "audio",
      selectionType: "musicZone",
      storage: {
        stateKey: "musicZones",
        type: "array",
        stateRoot: "audioLayers",
      },
      spatial: false, // defined by polygon
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Music Zone",
        },
        {
          key: "trackId",
          label: "Track ID",
          type: "string",
          section: "Music",
          required: true,
          description: "Track ID from music.json",
        },
        {
          key: "combatTrackId",
          label: "Combat Track",
          type: "string",
          section: "Music",
          description: "Override track during combat",
        },
        {
          key: "priority",
          label: "Priority",
          type: "number",
          section: "Playback",
          default: 0,
          description: "Higher = takes precedence when overlapping",
          config: { min: 0, max: 100, step: 1 },
        },
        {
          key: "blendDistance",
          label: "Blend Distance",
          type: "number",
          section: "Playback",
          default: 10,
          description: "Transition blend (m)",
          config: { min: 0, max: 100, step: 1, unit: "m" },
        },
      ],
      defaults: {
        name: "Music Zone",
        trackId: "",
        priority: 0,
        blendDistance: 10,
        polygon: [],
      },
      marker: { shape: "billboard", scale: 1, yOffset: 2 },
      customEditor: "MusicZoneProperties",
    },

    // ───────── Ambient Zone ─────────
    // Matches AmbientZone (audio layer)
    {
      id: "ambientZone",
      name: "Ambient Zone",
      icon: "Volume2",
      color: "#14b8a6",
      paletteCategory: "audio",
      outlinerLayer: "audio",
      selectionType: "ambientZone",
      storage: {
        stateKey: "ambientZones",
        type: "array",
        stateRoot: "audioLayers",
      },
      spatial: false,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "Ambient Zone",
        },
        {
          key: "ambientType",
          label: "Ambient Type",
          type: "select",
          section: "General",
          required: true,
          default: "forest",
          config: {
            options: [
              { value: "forest", label: "Forest" },
              { value: "cave", label: "Cave" },
              { value: "ocean", label: "Ocean" },
              { value: "town", label: "Town" },
              { value: "desert", label: "Desert" },
              { value: "mountain", label: "Mountain" },
              { value: "swamp", label: "Swamp" },
              { value: "custom", label: "Custom" },
            ],
          },
        },
        {
          key: "volume",
          label: "Volume",
          type: "slider",
          section: "Playback",
          default: 0.8,
          config: { min: 0, max: 1, step: 0.05 },
        },
        {
          key: "falloffDistance",
          label: "Falloff Distance",
          type: "number",
          section: "Playback",
          default: 10,
          description: "Edge falloff (m)",
          config: { min: 0, max: 100, step: 1, unit: "m" },
        },
      ],
      defaults: {
        name: "Ambient Zone",
        ambientType: "forest",
        tracks: [],
        polygon: [],
        volume: 0.8,
        falloffDistance: 10,
      },
      marker: { shape: "billboard", scale: 1, yOffset: 2 },
      customEditor: "AmbientZoneProperties",
    },

    // ───────── SFX Trigger ─────────
    // Matches SFXTrigger (audio layer)
    {
      id: "sfxTrigger",
      name: "SFX Trigger",
      icon: "Bell",
      color: "#f59e0b",
      paletteCategory: "audio",
      outlinerLayer: "audio",
      selectionType: "sfxTrigger",
      storage: {
        stateKey: "sfxTriggers",
        type: "array",
        stateRoot: "audioLayers",
      },
      spatial: true,
      fields: [
        {
          key: "name",
          label: "Name",
          type: "string",
          section: "General",
          required: true,
          default: "SFX Trigger",
        },
        {
          key: "soundPath",
          label: "Sound Path",
          type: "string",
          section: "Sound",
          required: true,
          description: "Sound asset path",
        },
        {
          key: "description",
          label: "Description",
          type: "string",
          section: "Sound",
          description: "Description for AI generation",
        },
        {
          key: "radius",
          label: "Radius",
          type: "number",
          section: "Playback",
          default: 10,
          description: "Audible radius (m)",
          config: { min: 1, max: 200, step: 1, unit: "m" },
        },
        {
          key: "volume",
          label: "Volume",
          type: "slider",
          section: "Playback",
          default: 0.8,
          config: { min: 0, max: 1, step: 0.05 },
        },
        {
          key: "looping",
          label: "Loop",
          type: "boolean",
          section: "Playback",
          default: false,
        },
        {
          key: "position",
          label: "Position",
          type: "position",
          section: "Transform",
          default: { x: 0, y: 0, z: 0 },
        },
      ],
      defaults: {
        name: "SFX Trigger",
        soundPath: "",
        radius: 10,
        volume: 0.8,
        looping: false,
        position: { x: 0, y: 0, z: 0 },
      },
      marker: {
        shape: "sphere",
        scale: 0.5,
        yOffset: 0.5,
        showRadius: true,
        radiusField: "radius",
      },
      customEditor: "SFXTriggerProperties",
    },
  ],
};
