/**
 * Shared vegetation exclusion filtering — used by both World Studio
 * (TileBasedTerrain.tsx) and the game client (TerrainSystem).
 *
 * Trees generated by procgen are filtered to remove those near towns,
 * buildings, roads, mines, and placed entities. The same algorithm
 * runs in both environments so staging matches World Studio exactly.
 */

// ---------------------------------------------------------------------------
// Noise functions — deterministic, position-based
// ---------------------------------------------------------------------------

/** Spatial hash for value noise (shader-style, deterministic) */
function vegHash(x: number, z: number): number {
  const n = Math.sin(x * 127.1 + z * 311.7) * 43758.5453;
  return n - Math.floor(n);
}

/** Bicubic-interpolated value noise [0..1] */
function vegSmoothNoise(x: number, z: number): number {
  const ix = Math.floor(x),
    iz = Math.floor(z);
  const fx = x - ix,
    fz = z - iz;
  const sx = fx * fx * (3 - 2 * fx);
  const sz = fz * fz * (3 - 2 * fz);
  return (
    vegHash(ix, iz) * (1 - sx) * (1 - sz) +
    vegHash(ix + 1, iz) * sx * (1 - sz) +
    vegHash(ix, iz + 1) * (1 - sx) * sz +
    vegHash(ix + 1, iz + 1) * sx * sz
  );
}

/** 3-octave FBM [0..1] for organic town boundary distortion */
export function vegFbm(x: number, z: number): number {
  return (
    vegSmoothNoise(x, z) * 0.5714 +
    vegSmoothNoise(x * 2, z * 2) * 0.2857 +
    vegSmoothNoise(x * 4, z * 4) * 0.1429
  );
}

/** Deterministic per-position random [0..1] for survival roll */
export function vegRand(x: number, z: number): number {
  const n = Math.sin(x * 12.9898 + z * 78.233) * 43758.5453;
  return n - Math.floor(n);
}

/** Hermite smoothstep (clamped) */
export function vegSmoothstep(edge0: number, edge1: number, x: number): number {
  const t = Math.max(0, Math.min(1, (x - edge0) / (edge1 - edge0)));
  return t * t * (3 - 2 * t);
}

// ---------------------------------------------------------------------------
// Constants — tuned for RuneScape-style settlement → wilderness
// ---------------------------------------------------------------------------

/** Noise frequency (features ~14m, subtle wobble) */
export const VEG_NOISE_FREQ = 0.07;
/** ±6m town boundary wobble (subtle, not chaotic) */
export const VEG_NOISE_AMP = 6;
/** Fraction of safeZone ≈ zero density */
export const VEG_TOWN_INNER_FRAC = 0.3;
/** Fraction of safeZone ≈ full density */
export const VEG_TOWN_OUTER_FRAC = 1.5;
/** Smallest trees at town fringe */
export const VEG_MIN_EDGE_SCALE = 0.35;

// ---------------------------------------------------------------------------
// Exclusion data types
// ---------------------------------------------------------------------------

/** Precomputed circle exclusion (squared radius for fast check) */
export interface ExclusionCircleSq {
  x: number;
  z: number;
  rSq: number;
}

/** Precomputed road segment for point-to-segment distance */
export interface ExclusionRoadSeg {
  ax: number;
  az: number;
  abx: number;
  abz: number;
  abLenSq: number;
  hwSq: number;
}

/** Precomputed town gradient parameters */
export interface ExclusionTownGradient {
  x: number;
  z: number;
  innerR: number;
  outerR: number;
  maxDSq: number;
}

/** All precomputed exclusion data, ready for fast per-tree checks */
export interface PrecomputedExclusions {
  circles: ExclusionCircleSq[];
  roadSegs: ExclusionRoadSeg[];
  towns: ExclusionTownGradient[];
}

// ---------------------------------------------------------------------------
// Exclusion builder — converts raw game data into precomputed form
// ---------------------------------------------------------------------------

/** Raw exclusion input (matches World Studio's VegetationExclusions) */
export interface VegetationExclusionInput {
  circles: Array<{ x: number; z: number; radius: number }>;
  roads: Array<{ path: Array<{ x: number; z: number }>; halfWidth: number }>;
  towns?: Array<{ x: number; z: number; safeZoneRadius: number }>;
}

/** Convert raw exclusion input into precomputed form */
export function precomputeExclusions(
  input: VegetationExclusionInput,
): PrecomputedExclusions {
  const circles = input.circles.map((c) => ({
    x: c.x,
    z: c.z,
    rSq: c.radius * c.radius,
  }));

  const roadSegs: ExclusionRoadSeg[] = [];
  for (const road of input.roads) {
    for (let i = 0; i < road.path.length - 1; i++) {
      const a = road.path[i],
        b = road.path[i + 1];
      const abx = b.x - a.x,
        abz = b.z - a.z;
      const abLenSq = abx * abx + abz * abz;
      if (abLenSq < 0.001) continue;
      roadSegs.push({
        ax: a.x,
        az: a.z,
        abx,
        abz,
        abLenSq,
        hwSq: road.halfWidth * road.halfWidth,
      });
    }
  }

  const towns = (input.towns ?? []).map((t) => {
    const innerR = t.safeZoneRadius * VEG_TOWN_INNER_FRAC;
    const outerR = t.safeZoneRadius * VEG_TOWN_OUTER_FRAC;
    return {
      x: t.x,
      z: t.z,
      innerR,
      outerR,
      maxDSq: (outerR + VEG_NOISE_AMP) * (outerR + VEG_NOISE_AMP),
    };
  });

  return { circles, roadSegs, towns };
}

// ---------------------------------------------------------------------------
// Tree filtering
// ---------------------------------------------------------------------------

/** Minimal tree interface for filtering — works with any tree data shape */
export interface FilterableTree {
  x: number;
  z: number;
  /** Mutable — town gradient tapering modifies this */
  sc: number;
}

/**
 * Filter trees by exclusion zones. Returns a NEW array of surviving trees.
 * Trees near buildings/roads are hard-removed; trees near town centers are
 * probabilistically thinned with FBM-distorted boundaries and scale tapering.
 *
 * This is the single source of truth for vegetation filtering — used by both
 * World Studio's refreshVegetation and game client's TerrainSystem.
 */
export function filterTreesByExclusions<T extends FilterableTree>(
  trees: T[],
  exclusions: PrecomputedExclusions,
): T[] {
  const { circles, roadSegs, towns } = exclusions;
  if (circles.length === 0 && roadSegs.length === 0 && towns.length === 0) {
    return trees;
  }

  return trees.filter((tree) => {
    // ---- Layer 1: Hard exclusions (binary, no noise) ----
    // Buildings, resources, plazas — precise cutouts hidden by meshes.
    for (let i = 0; i < circles.length; i++) {
      const c = circles[i];
      const dx = tree.x - c.x,
        dz = tree.z - c.z;
      if (dx * dx + dz * dz < c.rSq) return false;
    }

    // Roads — point-to-segment distance
    for (let i = 0; i < roadSegs.length; i++) {
      const seg = roadSegs[i];
      const apx = tree.x - seg.ax,
        apz = tree.z - seg.az;
      const t = Math.max(
        0,
        Math.min(1, (apx * seg.abx + apz * seg.abz) / seg.abLenSq),
      );
      const px = seg.ax + t * seg.abx - tree.x;
      const pz = seg.az + t * seg.abz - tree.z;
      if (px * px + pz * pz < seg.hwSq) return false;
    }

    // ---- Layer 2: Town density gradient (the only probabilistic layer) ----
    let townDensity = 1.0;
    for (let i = 0; i < towns.length; i++) {
      const town = towns[i];
      const dx = tree.x - town.x,
        dz = tree.z - town.z;
      const dSq = dx * dx + dz * dz;
      if (dSq > town.maxDSq) continue;

      const dist = Math.sqrt(dSq);
      const noise =
        (vegFbm(tree.x * VEG_NOISE_FREQ, tree.z * VEG_NOISE_FREQ) - 0.5) *
        2 *
        VEG_NOISE_AMP;
      const td = vegSmoothstep(town.innerR, town.outerR, dist + noise);
      if (td < townDensity) townDensity = td;
    }

    // Probabilistic thinning — only when inside a town's gradient
    if (townDensity < 0.999) {
      if (vegRand(tree.x, tree.z) > townDensity) return false;

      // Scale tapering: survivors near town are smaller ("younger growth")
      tree.sc *= VEG_MIN_EDGE_SCALE + (1 - VEG_MIN_EDGE_SCALE) * townDensity;
    }

    return true;
  });
}
