/**
 * Canonical allowlist of known ScriptGraph node types.
 *
 * This is the source of truth used by the server-side validator to reject
 * unknown node types before persisting a graph to the database. The list
 * mirrors the editor-side `nodeLibrary.ts` definitions — keep in sync.
 *
 * Phase 5.1 of packages/asset-forge/src/scripting/PLAN.md.
 */

export const NODE_TYPE_ALLOWLIST: ReadonlySet<string> = new Set<string>([
  // ---------------------------------------------------------------------
  // Triggers (onX)
  // ---------------------------------------------------------------------
  "trigger/onAggroTriggered",
  "trigger/onBankDeposit",
  "trigger/onBankOpened",
  "trigger/onBankWithdraw",
  "trigger/onCombatEnded",
  "trigger/onCombatStarted",
  "trigger/onCookingComplete",
  "trigger/onCorpseLoot",
  "trigger/onCraftingComplete",
  "trigger/onCustomEvent",
  "trigger/onDialogueEnded",
  "trigger/onDialogueResponse",
  "trigger/onDuelCompleted",
  "trigger/onEntityDamaged",
  "trigger/onEntityDeath",
  "trigger/onEntitySpawned",
  "trigger/onFiremakingSuccess",
  "trigger/onFunctionCall",
  "trigger/onFletchingComplete",
  "trigger/onInteract",
  "trigger/onItemCollected",
  "trigger/onItemDropped",
  "trigger/onItemEquipped",
  "trigger/onItemPickup",
  "trigger/onItemUsed",
  "trigger/onMobAggro",
  "trigger/onMobDamaged",
  "trigger/onMobKilled",
  "trigger/onMovementCompleted",
  "trigger/onMovementStarted",
  "trigger/onNPCInteraction",
  "trigger/onPlayerDamaged",
  "trigger/onPlayerDied",
  "trigger/onPlayerEnterZone",
  "trigger/onPlayerHealthChanged",
  "trigger/onPlayerJoined",
  "trigger/onPlayerLeaveZone",
  "trigger/onPlayerLeft",
  "trigger/onPlayerLevelUp",
  "trigger/onPlayerNearby",
  "trigger/onPlayerRespawned",
  "trigger/onPlayerSpawned",
  "trigger/onPrayerToggled",
  "trigger/onQuestComplete",
  "trigger/onQuestProgressed",
  "trigger/onQuestStarted",
  "trigger/onReady",
  "trigger/onResourceDepleted",
  "trigger/onResourceGathered",
  "trigger/onRunToggle",
  "trigger/onSmeltingComplete",
  "trigger/onSmithingComplete",
  "trigger/onStaminaDepleted",
  "trigger/onStoreTransaction",
  "trigger/onTeleportCompleted",
  "trigger/onTimer",
  "trigger/onTradeCompleted",

  // ---------------------------------------------------------------------
  // Conditions
  // ---------------------------------------------------------------------
  "condition/and",
  "condition/compareNumber",
  "condition/compareString",
  "condition/entityCount",
  "condition/entityExists",
  "condition/entityType",
  "condition/hasActiveBuff",
  "condition/hasCoins",
  "condition/hasEquipped",
  "condition/hasItem",
  "condition/hasQuestCompleted",
  "condition/healthCheck",
  "condition/isAlive",
  "condition/isInCombat",
  "condition/isInZone",
  "condition/isMobAlive",
  "condition/isPlayerInRange",
  "condition/isPrayerActive",
  "condition/not",
  "condition/or",
  "condition/questState",
  "condition/random",
  "condition/skillLevel",
  "condition/timeOfDay",
  "condition/variableExists",

  // ---------------------------------------------------------------------
  // Actions
  // ---------------------------------------------------------------------
  "action/activatePrayer",
  "action/applyBuff",
  "action/breakpoint",
  "action/completeQuest",
  "action/deactivatePrayer",
  "action/dealDamage",
  "action/debugDraw",
  "action/despawnAllInRadius",
  "action/despawnEntity",
  "action/dropItem",
  "action/emitCustomEvent",
  "action/equipItem",
  "action/getEntityProperty",
  "action/giveCoins",
  "action/giveItem",
  "action/giveXP",
  "action/healEntity",
  "action/incrementVariable",
  "action/lockMovement",
  "action/log",
  "action/moveEntity",
  "action/openBank",
  "action/openShop",
  "action/playAnimation",
  "action/playMusic",
  "action/playSound",
  "action/progressQuest",
  "action/removeBuff",
  "action/removeItem",
  "action/sendChat",
  "action/setAggroRange",
  "action/setDialogueOverride",
  "action/setEntityProperty",
  "action/setMovementSpeed",
  "action/setRespawnTime",
  "action/setVariable",
  "action/showDialogue",
  "action/showNotification",
  "action/spawnItem",
  "action/spawnMob",
  "action/spawnNPC",
  "action/spawnParticle",
  "action/startCombat",
  "action/startDialogueTree",
  "action/startQuest",
  "action/stopCombat",
  "action/stopMusic",
  "action/teleportPlayer",
  "action/unlockMovement",
  "action/wait",

  // ---------------------------------------------------------------------
  // Flow control
  // ---------------------------------------------------------------------
  "flow/branch",
  "flow/callGraph",
  "flow/delay",
  "flow/doN",
  "flow/flipFlop",
  "flow/forEach",
  "flow/forLoop",
  "flow/gate",
  "flow/multiGate",
  "flow/sequence",
  "flow/whileLoop",

  // ---------------------------------------------------------------------
  // Math
  // ---------------------------------------------------------------------
  "math/abs",
  "math/add",
  "math/booleanLogic",
  "math/ceil",
  "math/clamp",
  "math/compare",
  "math/distance3D",
  "math/divide",
  "math/floor",
  "math/lerp",
  "math/max",
  "math/min",
  "math/modulo",
  "math/multiply",
  "math/negate",
  "math/power",
  "math/randomRange",
  "math/round",
  "math/sqrt",
  "math/subtract",
  "math/toNumber",
  "math/toString",
  "math/vectorAdd",
  "math/vectorCross",
  "math/vectorDot",
  "math/vectorLength",
  "math/vectorLerp",
  "math/vectorNormalize",
  "math/vectorScale",
  "math/vectorSubtract",

  // ---------------------------------------------------------------------
  // Variables
  // ---------------------------------------------------------------------
  "variable/get",
  "variable/increment",
  "variable/set",

  // ---------------------------------------------------------------------
  // Data (pure data nodes consumed by downstream inputs)
  // ---------------------------------------------------------------------
  "data/arrayAdd",
  "data/arrayContains",
  "data/arrayGetAt",
  "data/arrayLength",
  "data/arrayRemove",
  "data/arraySlice",
  "data/breakVector3",
  "data/castToMob",
  "data/castToNPC",
  "data/castToPlayer",
  "data/constant",
  "data/findClosestEntity",
  "data/findEntitiesInRadius",
  "data/getEntityProperty",
  "data/getEntityPosition",
  "data/getEntityRotation",
  "data/getPlayerEquipment",
  "data/getPlayerHealth",
  "data/getPlayerInventory",
  "data/getPlayerStats",
  "data/getTime",
  "data/getTriggerData",
  "data/isLineOfSight",
  "data/lineTrace",
  "data/makeVector3",
  "data/sphereCast",
  "data/toBoolean",
]);

/**
 * Returns true if `type` is a recognised node type.
 * Comparison is exact (no prefix matching) to prevent future additions from
 * slipping through without explicit acknowledgement.
 */
export function isAllowedNodeType(type: string): boolean {
  return NODE_TYPE_ALLOWLIST.has(type);
}
